name: Setup SUI CLI
description: 'Setup Sui CLI'

inputs:
  sui-version:
    description: 'The version of Sui CLI to install'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Cache Sui binaries
      id: cache-sui
      uses: useblacksmith/cache@v5
      with:
        path: sui-binaries/
        key: sui-${{ inputs.sui-version }}

    - name: Install Dependencies
      shell: bash
      if: steps.cache-sui.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev

    - name: Download and Install Sui
      shell: bash
      if: steps.cache-sui.outputs.cache-hit != 'true'
      run: |
        curl -L -o sui-${{ inputs.sui-version }}-ubuntu-x86_64.tgz https://github.com/MystenLabs/sui/releases/download/${{ inputs.sui-version }}/sui-${{ inputs.sui-version }}-ubuntu-x86_64.tgz
        mkdir -p sui-binaries
        tar -xvf sui-${{ inputs.sui-version }}-ubuntu-x86_64.tgz -C sui-binaries
        rm -rf sui-${{ inputs.sui-version }}-ubuntu-x86_64.tgz

    - name: Save Sui binaries
      if: steps.cache-sui.outputs.cache-hit != 'true'
      id: cache-sui-save
      uses: useblacksmith/cache@v5
      with:
        path: sui-binaries/
        key: sui-${{ inputs.sui-version }}

    - name: Add Sui binaries to PATH
      shell: bash
      run: |
        sudo cp ./sui-binaries/sui /usr/local/bin/sui
        sudo cp ./sui-binaries/sui-debug /usr/local/bin/sui-debug
