[package]
name = "RelayerDiscovery"
version = "0.1.0"
edition = "2024"

[dependencies]
VersionControl = { local = "../version_control" }
AxelarGateway = { local = "../axelar_gateway" }

[addresses]
relayer_discovery = "0xaa"
clock = "0x6"
