name: Install Sui CLI
description: 'Install Sui CLI'

inputs:
  sui-version:
    description: 'Sui Version'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev
        echo ${{ inputs.sui-version }}

    - name: Cache Sui binaries
      id: cache-sui
      uses: actions/cache@v4
      with:
        path: sui-binaries/
        key: sui-${{ inputs.sui-version }}

    - name: Download and Install Sui
      shell: bash
      if: steps.cache-sui.outputs.cache-hit != 'true'
      run: |
        mkdir -p sui-binaries
        curl -L -o sui-${{ inputs.sui-version }}-ubuntu-x86_64.tgz https://github.com/MystenLabs/sui/releases/download/${{ inputs.sui-version }}/sui-${{ inputs.sui-version }}-ubuntu-x86_64.tgz
        tar -xvf sui-${{ inputs.sui-version }}-ubuntu-x86_64.tgz -C sui-binaries
        rm -rf sui-${{ inputs.sui-version }}-ubuntu-x86_64.tgz

    - name: Save Sui binaries
      if: steps.cache-sui.outputs.cache-hit != 'true'
      id: cache-sui-save
      uses: actions/cache@v4
      with:
        path: sui-binaries/
        key: sui-${{ inputs.sui-version }}

    - name: Add Sui binaries to PATH
      shell: bash
      run: |
        sudo cp ./sui-binaries/sui /usr/local/bin/sui
        sudo cp ./sui-binaries/sui-debug /usr/local/bin/sui-debug
