name: Install Node Dependencies
description: 'Install Node Dependencies'

inputs:
  node-version:
    description: 'Node Version'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Parse input
      shell: bash
      run: echo NODE_VERSION=${ inputs.node-version } >> GITHUB_ENV

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: npm ci