name: Install Node Dependencies
description: 'Install Node Dependencies'

inputs:
  node-version:
    description: 'Node Version'
    required: true

runs:
  using: 'composite'

  steps:
    - name: test
      run: echo ${{ inputs.node-version }}
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: npm ci