name: Install Dependencies
description: 'Setup Sui CLI and install dependencies'

runs:
  using: 'composite'

  steps:
    - name: Assign Sui Version
      shell: bash
      run: echo "SUI_VERSION=mainnet-v1.31.1" >> $GITHUB_ENV

    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev

    - name: Cache Sui binaries
      id: cache-sui
      uses: actions/cache@v4
      with:
        path: sui-binaries/
        key: sui-${{ env.SUI_VERSION }}

    - name: Download and Install Sui
      shell: bash
      if: steps.cache-sui.outputs.cache-hit != 'true'
      run: |
        curl -L -o sui-${{ env.SUI_VERSION }}-ubuntu-x86_64.tgz https://github.com/MystenLabs/sui/releases/download/${{ env.SUI_VERSION }}/sui-${{ env.SUI_VERSION }}-ubuntu-x86_64.tgz
        tar -xvf sui-${{ env.SUI_VERSION }}-ubuntu-x86_64.tgz
        mkdir -p sui-binaries
        mv ./sui ./sui-binaries/
        mv ./sui-debug ./sui-binaries/
        rm -rf sui-${{ env.SUI_VERSION }}-ubuntu-x86_64.tgz

    - name: Save Sui binaries
      if: steps.cache-sui.outputs.cache-hit != 'true'
      id: cache-sui-save
      uses: actions/cache@v4
      with:
        path: sui-binaries/
        key: sui-${{ env.SUI_VERSION }}

    - name: Add Sui binaries to PATH
      shell: bash
      run: |
        sudo cp ./sui-binaries/sui /usr/local/bin/sui
        sudo cp ./sui-binaries/sui-debug /usr/local/bin/sui-debug

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      shell: bash
      run: npm ci
