[package]
name = "InterchainTokenService"
version = "0.1.0"
edition = "2024"

[dependencies]
AxelarGateway = { local = "../axelar_gateway" }
Abi = { local = "../abi" }
Utils = { local = "../utils" }
VersionControl = { local = "../version_control" }
RelayerDiscovery = { local = "../relayer_discovery" }

[addresses]
interchain_token_service = "0xa5"
