# This workflow concerns the preparation of the `changeset` PR and keeping it updated by tracking the changes on `main` branch.
name: Create Release PR

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  create-release-pr:
    name: Create Release PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Check for changeset files
        run: |
          if ! ls .changeset/*.md | grep -q '\.changeset\/[a-z-]\+\.md$'; then
            echo "No changeset files found. Exiting workflow."
            exit 1
          fi

          echo "Changeset files found. Continuing with the workflow."

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          install-nodejs: 'true'

      # Keep the version of the PRs up-to-date
      - name: Create Release Pull Request
        id: release-pr
        uses: changesets/action@aba318e9165b45b7948c60273e0b72fce0a64eb9 # v1.4.7
        with:
          branch: 'main'
          title: 'chore(release): bump version and update changelog'
          commit: 'chore(release): bump version and update changelog'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
