name: Find Limits

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  limits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          install-sui: 'true'
          install-nodejs: 'true'
          
      - name: Build TS and Move Modules
        run: npm run build

      - name: Initialize Sui Config
        run: echo -e "y\n\n1" | sui client envs

      - name: Run Localnet
        run: nohup sh -c "RUST_LOG="off,sui_node=info" sui start --with-faucet --force-regenesis" > nohup.out 2> nohup.err < /dev/null &

      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Create limits
        run: node scripts/limits.js >> comment.md

      - name: Find Code Coverage comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Code Coverage Summary

      - name: Create or update Code Coverage comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: ./comment.md
          edit-mode: replace
