name: Linting

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Node.js and its dependencies
      - name: Get NodeJS Version
        shell: bash
        run: |
          NODEJS_VERSION=$(jq -r '.engines.node' "package.json")
          echo "NODEJS_VERSION=$NODEJS_VERSION" >> $GITHUB_ENV

      - name: Setup node.js and install dependencies
        uses: ./.github/actions/nodejs-ci
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      - name: Lint
        run: npm run lint

      - name: Prettier
        run: npm run prettier

      - name: Check for changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo Following files are changed by prettier...
            git status

            echo Changes:
            git diff

            exit 1;
          else
            exit 0;
          fi
