name: Run Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SUI_VERSION: mainnet-v1.22.0

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Dependencies for Sui Binary
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Cache Sui binaries
        id: cache-sui
        uses: actions/cache@v4
        with:
          path: sui-binaries
          key: sui-${{ env.SUI_VERSION }}

      - name: Download and Install Sui
        if: steps.cache-sui.outputs.cache-hit != 'true'
        run: |
          curl -L -o sui-${SUI_VERSION}-ubuntu-x86_64.tgz https://github.com/MystenLabs/sui/releases/download/${SUI_VERSION}/sui-${SUI_VERSION}-ubuntu-x86_64.tgz
          tar -xvf sui-${SUI_VERSION}-ubuntu-x86_64.tgz
          mkdir -p sui-binaries
          mv ./sui sui-binaries/
          mv ./sui-debug sui-binaries/
          rm -rf sui-${SUI_VERSION}-ubuntu-x86_64.tgz

      - name: Save Sui binaries to cache
        if: steps.cache-sui.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: sui-binaries
          key: sui-${{ env.SUI_VERSION }}

      - name: Add Sui binaries to PATH
        run: |
          sudo mv ./sui-binaries/sui /usr/local/bin/sui
          sudo mv ./sui-binaries/sui-debug /usr/local/bin/sui-debug

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        timeout-minutes: 15
        run: npm run test
