name: Run Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Dependencies for Sui Binary
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Download and Install Sui Binary
        env:
          SUI_VERSION: mainnet-v1.22.0
        run: |
          wget https://github.com/MystenLabs/sui/releases/download/${SUI_VERSION}/sui-${SUI_VERSION}-ubuntu-x86_64.tgz
          tar -xvf sui-${SUI_VERSION}-ubuntu-x86_64.tgz
          sudo mv ./target/release/sui-test-validator-ubuntu-x86_64 /usr/local/bin/sui-test-validator
          sudo mv ./target/release/sui-ubuntu-x86_64 /usr/local/bin/sui
          rm -rf sui-${SUI_VERSION}-ubuntu-x86_64.tgz

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        timeout-minutes: 15
        run: npm run test
