name: Move Tests

on:
  pull_request:
  push:
    branches:
      - main
      - releases/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-move:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Sui CLI
        uses: ./.github/actions/install-sui-cli
        with:
          sui-version: $(jq -r '.SUI_VERSION' version.json)

      - name: Setup Node Dependencies
        uses: ./.github/actions/install-node-dependencies
        with:
          node-version: $(jq -r '.NODE_VERSION' version.json)

      - name: Build Move Modules
        run: npm run build-move

      - name: Test
        run: npm run test-move
