name: Move Tests

on:
  pull_request:
  push:
    branches:
      - main
      - releases/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-move:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Sui dependencies
      - name: Setup the required tools (sui, nodejs)
        uses: ./.github/actions/setup-tools
        with:
          install-sui: 'true'
          install-nodejs: 'true'

      - name: Build Move Modules
        run: npm run build-move

      - name: Test
        run: npm run test-move
